# Generated by Django 6.0.1 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_chart_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_hash',
            field=models.CharField(blank=True, help_text='Client-derived authentication hash', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auth_salt',
            field=models.CharField(blank=True, help_text='Salt for authentication hash (base64, 16 bytes)', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_user_key',
            field=models.BinaryField(blank=True, help_text='Per-user encryption key, encrypted with KEK derived from password', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encryption_migrated',
            field=models.BooleanField(default=False, help_text='Whether user has migrated to per-user encryption'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kek_salt',
            field=models.CharField(blank=True, help_text='Salt for KEK derivation (base64, 16 bytes)', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_version',
            field=models.PositiveIntegerField(default=1, help_text='Key version for rotation support'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_on_app_open',
            field=models.BooleanField(default=False, help_text='Automatically sync when opening app'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_reminder_enabled',
            field=models.BooleanField(default=True, help_text='Enable daily sync reminder notification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_reminder_hour',
            field=models.PositiveSmallIntegerField(default=9, help_text='Hour for sync reminder (0-23)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_reminder_minute',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minute for sync reminder (0-59)'),
        ),
    ]
