# Generated by Django 6.0.1 on 2026-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_kek_encryption_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo_user',
            field=models.BooleanField(default=False, help_text='Demo user created by generate_demo_data command'),
        ),
    ]
