# Generated by Django 6.0.3 on 2026-04-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_demo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_aggregation',
            field=models.CharField(choices=[('last', 'Last value'), ('min', 'Minimum'), ('max', 'Maximum'), ('avg', 'Average')], default='last', help_text='How to pick the representative value for each month', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sync_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable daily sync reminder notification'),
        ),
    ]
