# Generated by Django 6.0.3 on 2026-07-12 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0003_alter_broker_integration_type_ebicscredential'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='ebics_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='brokers.ebicscredential'),
        ),
    ]
