"""
Morgan Stanley at Work — headless-browser login.

Why a browser at all? MS mints the GraphQL JWT via a session-bound REST call
(`POST /rest/participant/v2/auth/tokens`) that is only issued after the legacy
`userLogin.do` servlet login + (on an untrusted device) a GWT-RPC TOTP step, and
the login form carries a Symantec VIP device fingerprint generated by obfuscated
JS that we cannot reproduce server-side. Rather than replay a static fingerprint
(a fraud-anomaly risk), we let a real Chromium engine perform the login: it
generates a genuine, correctly-timestamped fingerprint, we auto-fill the TOTP
from the stored seed, and we persist the browser storage state so the device
stays "trusted" across syncs. See docs/morgan-stanley-integration.md.

This module is import-safe without Playwright installed; the dependency is only
required when `browser_login()` is actually called.

NOTE ON SELECTORS: the `userLogin.do` field selectors are high-confidence (the
names come from observed form submissions: `account_number`, `password`). The
TOTP / "trust this device" page is GWT-rendered and its DOM was not captured, so
those selectors are best-effort with fallbacks. Run once with MS_HEADLESS=0 to
watch the flow and adjust `_TOTP_*` / `_TRUST_*` selectors if needed.
"""
import hashlib
import logging
import os
import re
import time
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

BASE_URL = "https://atwork.morganstanley.com"
LOGIN_URL = f"{BASE_URL}/solium/servlet/userLogin.do"
DASHBOARD_URL = f"{BASE_URL}/solium/servlet/ui"
TOKEN_PATH = "/rest/participant/v2/auth/tokens"
REGISTER_DEVICE_PATH = "/rest/participant/v2/device-registration/register-device"

# --- Proven selectors / JS for the live login flow (reverse-engineered 2026-05) ---
# Hide the automation signals MS/Akamai+Symantec score on (the only one that
# matters is navigator.webdriver; do NOT fake navigator.plugins — the RSA
# footprint code reads plugin.filename and crashes on faked entries).
STEALTH_JS = (
    "Object.defineProperty(navigator,'webdriver',{get:()=>undefined});"
    "window.chrome = window.chrome || {runtime:{}};"
)
_SEL_USER = "#account_number_input"
_SEL_PASS = "#password"
_SEL_REMEMBER = "#remember_checkbox"
_SEL_SUBMIT = "#submit-btn"
_SEL_TOTP = "#totp-security-code-input"
_SEL_VERIFY = "#gwt-debug-verifyButton"
# The 'Yes, trust this device' button's accessible name is its text (its arialabel
# is misspelled, so ignored). Match on the distinctive 'Yes ... trust' so it can
# never resolve to the 'Why am I being asked...' explainer (name "Link, why...") or 'No'.
_TRUST_BUTTON_RE = re.compile(r"yes,?\s*trust", re.I)
# The login page builds + attaches the device fingerprints in these synchronous
# functions, then submits via Login(); a raw button click skips them and MS
# rejects the login as invalid.
_IADFP_READY_JS = ("() => { try { IaDfp.setEnhancedFingerprint(true);"
                   " return (IaDfp.readFingerprint() || '').length > 0; } catch (e) { return false; } }")
_INJECT_FP_JS = ("() => { const b = document.querySelector('#submit-btn');"
                 " appendFootprintToForm(b); appendDeviceFingerprintToForm(b); }")
_INITDATA_JS = ("() => { const d = (window.SW && window.SW.initialData) || {};"
                " const a = d.activeAccount || {};"
                " return { employeePK: a.employeePK, accountPK: a.accountPK }; }")


class BrowserLoginUnavailable(RuntimeError):
    """Playwright (or its browser) is not installed/usable in this environment."""


class BrowserLoginError(RuntimeError):
    """The browser login flow failed (bad credentials, selector drift, timeout, ...)."""


def _state_path(state_dir: Optional[str], account_id: Any) -> Optional[Path]:
    """Per-account storage-state file. Keyed by FinancialAccount id."""
    if not state_dir or account_id is None:
        return None
    safe = hashlib.sha256(str(account_id).encode()).hexdigest()[:16]
    return Path(state_dir) / f"ms_account_{account_id}_{safe}.json"


def _generate_totp(totp_secret: str) -> str:
    import pyotp
    return pyotp.TOTP(totp_secret).now()


def _read_last_otp(sp: Optional[Path]) -> Optional[float]:
    """Epoch seconds of the last OTP for this account, or None."""
    if not sp:
        return None
    mp = sp.with_suffix(".lastotp")
    try:
        return float(mp.read_text().strip()) if mp.exists() else None
    except Exception:
        return None


def _write_last_otp(sp: Optional[Path]) -> None:
    if not sp:
        return
    mp = sp.with_suffix(".lastotp")
    try:
        mp.parent.mkdir(parents=True, exist_ok=True)
        mp.write_text(str(time.time()))
        os.chmod(mp, 0o600)
    except Exception as exc:
        logger.warning("MS 2FA: could not record OTP timestamp: %s", exc)


def browser_login(
    *,
    username: str,
    password: str,
    totp_secret: Optional[str] = None,
    totp_code: Optional[str] = None,
    state_dir: Optional[str] = None,
    account_id: Any = None,
    headless: Optional[bool] = None,
    allow_otp: Optional[bool] = None,
    force_otp: bool = False,
    timeout_ms: int = 60_000,
) -> Dict[str, Any]:
    """
    Perform a full MS at Work login in a headless browser and return the minted
    JWT plus the employee id needed for GraphQL.

    Returns: {'jwt_token': str, 'employee_id': str, 'account_pk': str|None,
              'state_persisted': bool}

    Raises BrowserLoginUnavailable if Playwright/browser is missing,
    BrowserLoginError on any login failure.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:  # pragma: no cover - depends on deploy image
        raise BrowserLoginUnavailable(
            "Playwright is not installed. Add `playwright` to requirements and run "
            "`playwright install --with-deps chromium`."
        ) from exc

    if headless is None:
        headless = os.environ.get("MS_HEADLESS", "1") != "0"

    sp = _state_path(state_dir, account_id)

    # OTP policy. Routine syncs MAY answer a 2FA challenge, but must not do it on
    # every check — repeated 2FA from the same source can itself trip fraud
    # detection (expected real cadence is ~monthly). So OTP is throttled to at most
    # once per MS_OTP_MIN_INTERVAL_HOURS (default 336h = 2 weeks): if MS challenges
    # again sooner, device-trust isn't holding and we fail loudly instead of
    # re-OTP-ing. MS_ALLOW_OTP=0 disables OTP entirely; force_otp / MS_FORCE_OTP=1
    # bypasses the throttle for a deliberate (re-)enrollment.
    if allow_otp is None:
        env_otp = os.environ.get("MS_ALLOW_OTP")
        allow_otp = (env_otp != "0") if env_otp is not None else True
    force_otp = force_otp or os.environ.get("MS_FORCE_OTP") == "1"
    otp_min_secs = float(os.environ.get("MS_OTP_MIN_INTERVAL_HOURS", "336")) * 3600

    captured: Dict[str, Any] = {}

    def _on_request(req):
        # Robust JWT capture: the SPA attaches the token as the Authorization header
        # on its /rest and /graphql calls. Request headers aren't evicted on
        # navigation (unlike response bodies, which break Response.json()), so this
        # is reliable.
        if "jwt" in captured:
            return
        try:
            auth = req.headers.get("authorization", "")
            tok = auth[7:] if auth[:7].lower() == "bearer " else auth
            if tok.startswith("eyJ") and ("/rest/participant" in req.url or "/graphql" in req.url):
                captured["jwt"] = tok
        except Exception:
            pass

    def _on_response(resp):
        # Log every device registration so we can monitor how often it happens.
        try:
            if resp.request.method == "POST" and REGISTER_DEVICE_PATH in resp.url:
                reason = ""
                try:
                    reason = (resp.json().get("data") or {}).get("reasonDescription", "")
                except Exception:
                    pass
                captured["device_registered"] = True
                logger.warning(
                    "MS 2FA: device registration processed (account_id=%s, status=%s) %s",
                    account_id, resp.status, reason,
                )
        except Exception:
            pass

    try:
        with sync_playwright() as p:
            # Akamai/Symantec drop headless Chromium and flag automation, so we turn
            # off the AutomationControlled flag and mask navigator.webdriver.
            # NOTE: headless is reliably BLOCKED by Akamai — run headful (the server
            # needs a display / Xvfb, or Chromium's --headless=new). See the docs.
            browser = p.chromium.launch(
                headless=headless,
                args=["--disable-blink-features=AutomationControlled"],
            )
            ctx_kwargs: Dict[str, Any] = {"locale": "en-US"}
            # Use the bundled Chromium's own UA but strip the "Headless" token so it
            # matches headful Chrome and stays consistent with every other signal the
            # same Chromium produces (platform, canvas, WebGL, client hints). This
            # removes the "HeadlessChrome" bot-detection tell without faking an
            # inconsistent UA string.
            try:
                probe = browser.new_context()
                ua = probe.new_page().evaluate("() => navigator.userAgent")
                probe.close()
                if ua and "Headless" in ua:
                    ctx_kwargs["user_agent"] = ua.replace("HeadlessChrome", "Chrome")
                    logger.info("MS browser: using de-headlessed UA: %s", ctx_kwargs["user_agent"])
            except Exception as exc:
                logger.warning("MS browser: could not read/sanitize UA: %s", exc)
            if sp and sp.exists():
                ctx_kwargs["storage_state"] = str(sp)
                logger.info("MS browser: loaded device-trust state from %s", sp)
            context = browser.new_context(**ctx_kwargs)
            context.add_init_script(STEALTH_JS)
            page = context.new_page()
            page.on("request", _on_request)
            page.on("response", _on_response)
            page.set_default_timeout(timeout_ms)

            logger.info("MS browser: navigating to login (headless=%s)", headless)
            page.goto(LOGIN_URL, wait_until="load")
            page.wait_for_timeout(1500)

            # If a persisted trusted session lands us on the dashboard, skip login.
            if "/servlet/ui" not in page.url:
                # Wait until the Symantec device fingerprint can be computed.
                for _ in range(15):
                    try:
                        if page.evaluate(_IADFP_READY_JS):
                            break
                    except Exception:
                        pass
                    page.wait_for_timeout(1000)

                # Type like a human — this login is keystroke-driven; .fill() is rejected.
                try:
                    page.click(_SEL_USER)
                    page.locator(_SEL_USER).press_sequentially(username, delay=60)
                    page.click(_SEL_PASS)
                    page.locator(_SEL_PASS).press_sequentially(password, delay=60)
                except Exception as exc:
                    raise BrowserLoginError(f"Could not fill the login form: {exc}")
                try:
                    page.check(_SEL_REMEMBER)
                    logger.info("MS browser: 'remember me' checked")
                except Exception:
                    pass

                # Build + attach the device fingerprints via the page's own functions,
                # then submit through Login(). A raw submit omits ms_rsa_footprint /
                # symantec_device_fingerprint and MS rejects the login.
                try:
                    page.evaluate(_INJECT_FP_JS)
                    page.evaluate("() => Login()")
                except Exception as exc:
                    raise BrowserLoginError(f"Could not run the page login/fingerprint JS: {exc}")

                # Wait for the TOTP page, the dashboard, or a login error.
                deadline = time.monotonic() + 45
                while time.monotonic() < deadline:
                    if "/servlet/ui" in page.url:
                        break
                    if "loginError" in page.url:
                        raise BrowserLoginError(
                            "MS rejected the login (bad credentials, or the device "
                            "fingerprint was not attached)."
                        )
                    try:
                        if page.locator(_SEL_TOTP).first.is_visible():
                            break
                    except Exception:
                        pass
                    page.wait_for_timeout(500)

            # Handle a 2FA (TOTP) challenge if the device is not trusted.
            totp_visible = False
            try:
                totp_visible = page.locator(_SEL_TOTP).first.is_visible()
            except Exception:
                pass
            if totp_visible:
                logger.warning("MS 2FA: OTP challenge presented (account_id=%s).", account_id)
                if not allow_otp:
                    raise BrowserLoginError(
                        "OTP challenge presented but OTP is disabled (MS_ALLOW_OTP=0)."
                    )
                # Throttle: refuse to OTP again too soon — repeated 2FA is itself a
                # fraud signal and means device-trust isn't sticking.
                last_otp = _read_last_otp(sp)
                if last_otp is not None and not force_otp:
                    since_h = (time.time() - last_otp) / 3600
                    if since_h < otp_min_secs / 3600:
                        raise BrowserLoginError(
                            f"OTP challenged again only {since_h:.1f}h after the last OTP "
                            f"(throttle {otp_min_secs / 3600:.0f}h, expected ~monthly). "
                            "Device-trust isn't holding — refusing to re-OTP to avoid fraud "
                            "detection. Check the MS_BROWSER_STATE_DIR volume persistence, or "
                            "re-enroll deliberately with MS_FORCE_OTP=1."
                        )
                code = totp_code or (totp_secret and _generate_totp(totp_secret))
                if not code:
                    raise BrowserLoginError(
                        "TOTP challenge presented but no totp_secret/totp_code available."
                    )
                logger.info("MS 2FA: entering TOTP code (account_id=%s).", account_id)
                page.fill(_SEL_TOTP, code)
                page.click(_SEL_VERIFY)
                # Accept the 'trust this device' prompt so future syncs skip OTP.
                # Exact match — a substring on 'trust' would hit the explainer link.
                try:
                    trust = page.get_by_role("button", name=_TRUST_BUTTON_RE)
                    trust.wait_for(state="visible", timeout=20_000)
                    trust.click()
                    logger.warning("MS 2FA: 'trust this device' accepted (account_id=%s).", account_id)
                except Exception:
                    logger.info("MS 2FA: no trust-device prompt appeared (account_id=%s).", account_id)
                _write_last_otp(sp)
                logger.warning(
                    "MS 2FA: OTP submitted (account_id=%s); next OTP throttled for ~%.0fh.",
                    account_id, otp_min_secs / 3600,
                )
            else:
                logger.info("MS 2FA: no OTP challenge — device trusted (account_id=%s).", account_id)

            # Make sure we reached the authenticated dashboard (or its requirements
            # interstitial — both live under /servlet/ui).
            try:
                page.wait_for_url("**/servlet/ui**", timeout=timeout_ms)
            except Exception:
                if "/servlet/ui" not in page.url:
                    raise BrowserLoginError(
                        f"Login did not reach the dashboard (still at {page.url}). "
                        "Likely bad credentials, an unhandled challenge, or selector drift."
                    )

            # Capture the JWT from an outgoing Authorization header (set by _on_request).
            # The SPA fires authenticated /rest + /graphql calls on dashboard load; if
            # we haven't seen one yet, (re)load the dashboard and wait for it.
            if "jwt" not in captured:
                try:
                    page.goto(DASHBOARD_URL, wait_until="domcontentloaded")
                except Exception:
                    pass
                wait_until = time.monotonic() + 20
                while "jwt" not in captured and time.monotonic() < wait_until:
                    page.wait_for_timeout(300)
            jwt_token = captured.get("jwt")
            if not jwt_token:
                raise BrowserLoginError(
                    "Login reached the dashboard but no JWT Authorization header was seen "
                    "on any /rest or /graphql request."
                )

            # Read identifiers straight from the page's SW.initialData.
            init = page.evaluate(_INITDATA_JS) or {}
            employee_pk = init.get("employeePK")
            account_pk = init.get("accountPK")
            if not employee_pk:
                raise BrowserLoginError("Login succeeded but employeePK was not found in SW.initialData.")

            # Persist the device-trust state for next time.
            state_persisted = False
            if sp:
                try:
                    sp.parent.mkdir(parents=True, exist_ok=True)
                    context.storage_state(path=str(sp))
                    os.chmod(sp, 0o600)
                    state_persisted = True
                    logger.info("MS browser: saved device-trust state to %s", sp)
                except Exception as exc:
                    logger.warning("MS browser: could not persist device-trust state: %s", exc)

            context.close()
            browser.close()

            return {
                "jwt_token": jwt_token,
                "employee_id": str(employee_pk),
                "account_pk": str(account_pk) if account_pk else None,
                "state_persisted": state_persisted,
            }
    except (BrowserLoginUnavailable, BrowserLoginError):
        raise
    except Exception as exc:
        # Surface Playwright launch/driver errors as "unavailable" so callers can
        # fall back to the manual-JWT path instead of hard-failing the sync.
        msg = str(exc).lower()
        if "executable doesn't exist" in msg or "playwright install" in msg or "browsertype.launch" in msg:
            raise BrowserLoginUnavailable(
                "Chromium for Playwright is not installed. Run "
                "`playwright install --with-deps chromium`."
            ) from exc
        raise BrowserLoginError(f"Browser login failed: {exc}") from exc
