"""
Morgan Stanley at Work — headless-browser login.

Why a browser at all? MS mints the GraphQL JWT via a session-bound REST call
(`POST /rest/participant/v2/auth/tokens`) that is only issued after the legacy
`userLogin.do` servlet login + (on an untrusted device) a GWT-RPC TOTP step, and
the login form carries a Symantec VIP device fingerprint generated by obfuscated
JS that we cannot reproduce server-side. Rather than replay a static fingerprint
(a fraud-anomaly risk), we let a real Chromium engine perform the login: it
generates a genuine, correctly-timestamped fingerprint, we auto-fill the TOTP
from the stored seed, and we persist the browser storage state so the device
stays "trusted" across syncs. See docs/morgan-stanley-integration.md.

This module is import-safe without Playwright installed; the dependency is only
required when `browser_login()` is actually called.

NOTE ON SELECTORS: the `userLogin.do` field selectors are high-confidence (the
names come from observed form submissions: `account_number`, `password`). The
TOTP / "trust this device" page is GWT-rendered and its DOM was not captured, so
those selectors are best-effort with fallbacks. Run once with MS_HEADLESS=0 to
watch the flow and adjust `_TOTP_*` / `_TRUST_*` selectors if needed.
"""
import hashlib
import logging
import os
import time
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

BASE_URL = "https://atwork.morganstanley.com"
LOGIN_URL = f"{BASE_URL}/solium/servlet/userLogin.do"
DASHBOARD_URL = f"{BASE_URL}/solium/servlet/ui"
TOKEN_PATH = "/rest/participant/v2/auth/tokens"
REGISTER_DEVICE_PATH = "/rest/participant/v2/device-registration/register-device"

# Login form (high confidence — from observed userLogin.do submissions)
_USER_SELECTORS = [
    "input[name='account_number']",
    "input#account_number",
    "input[name='username']",
]
_PASS_SELECTORS = [
    "input[name='password']",
    "input#password",
    "input[type='password']",
]
_SUBMIT_SELECTORS = [
    "button[type='submit']",
    "input[type='submit']",
    "#loginButton",
    "button:has-text('Log in')",
    "button:has-text('Sign in')",
]
# TOTP / device-trust (best-effort — verify against the live page)
_TOTP_SELECTORS = [
    "input[name*='totp' i]",
    "input[name*='code' i]",
    "input[autocomplete='one-time-code']",
    "input[type='tel']",
    "input[inputmode='numeric']",
]
_TOTP_SUBMIT_SELECTORS = [
    "button:has-text('Verify')",
    "button:has-text('Submit')",
    "button:has-text('Continue')",
    "button[type='submit']",
]
_TRUST_SELECTORS = [
    "input[type='checkbox'][name*='trust' i]",
    "input[type='checkbox'][name*='remember' i]",
    "label:has-text('trust this device') input[type='checkbox']",
]


class BrowserLoginUnavailable(RuntimeError):
    """Playwright (or its browser) is not installed/usable in this environment."""


class BrowserLoginError(RuntimeError):
    """The browser login flow failed (bad credentials, selector drift, timeout, ...)."""


def _state_path(state_dir: Optional[str], account_id: Any) -> Optional[Path]:
    """Per-account storage-state file. Keyed by FinancialAccount id."""
    if not state_dir or account_id is None:
        return None
    safe = hashlib.sha256(str(account_id).encode()).hexdigest()[:16]
    return Path(state_dir) / f"ms_account_{account_id}_{safe}.json"


def _generate_totp(totp_secret: str) -> str:
    import pyotp
    return pyotp.TOTP(totp_secret).now()


def _read_last_otp(sp: Optional[Path]) -> Optional[float]:
    """Epoch seconds of the last OTP for this account, or None."""
    if not sp:
        return None
    mp = sp.with_suffix(".lastotp")
    try:
        return float(mp.read_text().strip()) if mp.exists() else None
    except Exception:
        return None


def _write_last_otp(sp: Optional[Path]) -> None:
    if not sp:
        return
    mp = sp.with_suffix(".lastotp")
    try:
        mp.parent.mkdir(parents=True, exist_ok=True)
        mp.write_text(str(time.time()))
        os.chmod(mp, 0o600)
    except Exception as exc:
        logger.warning("MS 2FA: could not record OTP timestamp: %s", exc)


def _fill_first(page, selectors, value, timeout_ms) -> bool:
    """Try each selector; fill the first visible match. Returns True on success."""
    for sel in selectors:
        try:
            loc = page.locator(sel).first
            loc.wait_for(state="visible", timeout=timeout_ms)
            loc.fill(value)
            return True
        except Exception:
            continue
    return False


def _click_first(page, selectors, timeout_ms) -> bool:
    for sel in selectors:
        try:
            loc = page.locator(sel).first
            loc.wait_for(state="visible", timeout=timeout_ms)
            loc.click()
            return True
        except Exception:
            continue
    return False


def _visible_any(page, selectors, timeout_ms) -> bool:
    """True if any selector becomes visible within the timeout (short poll)."""
    for sel in selectors:
        try:
            page.locator(sel).first.wait_for(state="visible", timeout=timeout_ms)
            return True
        except Exception:
            continue
    return False


def browser_login(
    *,
    username: str,
    password: str,
    totp_secret: Optional[str] = None,
    totp_code: Optional[str] = None,
    state_dir: Optional[str] = None,
    account_id: Any = None,
    headless: Optional[bool] = None,
    allow_otp: Optional[bool] = None,
    force_otp: bool = False,
    timeout_ms: int = 60_000,
) -> Dict[str, Any]:
    """
    Perform a full MS at Work login in a headless browser and return the minted
    JWT plus the employee id needed for GraphQL.

    Returns: {'jwt_token': str, 'employee_id': str, 'account_pk': str|None,
              'state_persisted': bool}

    Raises BrowserLoginUnavailable if Playwright/browser is missing,
    BrowserLoginError on any login failure.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError as exc:  # pragma: no cover - depends on deploy image
        raise BrowserLoginUnavailable(
            "Playwright is not installed. Add `playwright` to requirements and run "
            "`playwright install --with-deps chromium`."
        ) from exc

    if headless is None:
        headless = os.environ.get("MS_HEADLESS", "1") != "0"

    sp = _state_path(state_dir, account_id)

    # OTP policy. Routine syncs MAY answer a 2FA challenge, but must not do it on
    # every check — repeated 2FA from the same source can itself trip fraud
    # detection (expected real cadence is ~monthly). So OTP is throttled to at most
    # once per MS_OTP_MIN_INTERVAL_HOURS (default 336h = 2 weeks): if MS challenges
    # again sooner, device-trust isn't holding and we fail loudly instead of
    # re-OTP-ing. MS_ALLOW_OTP=0 disables OTP entirely; force_otp / MS_FORCE_OTP=1
    # bypasses the throttle for a deliberate (re-)enrollment.
    if allow_otp is None:
        env_otp = os.environ.get("MS_ALLOW_OTP")
        allow_otp = (env_otp != "0") if env_otp is not None else True
    force_otp = force_otp or os.environ.get("MS_FORCE_OTP") == "1"
    otp_min_secs = float(os.environ.get("MS_OTP_MIN_INTERVAL_HOURS", "336")) * 3600

    captured: Dict[str, Any] = {}

    def _on_response(resp):
        # Selector-independent JWT capture: the page mints the token via this POST.
        try:
            if resp.request.method == "POST" and TOKEN_PATH in resp.url:
                data = resp.json()
                token = (data.get("accessToken") or {}).get("accessToken")
                if token:
                    captured["jwt"] = token
        except Exception:
            pass
        # Selector-independent device-registration tracking: log every time MS
        # registers/trusts this device, so we can monitor how often it happens.
        try:
            if resp.request.method == "POST" and REGISTER_DEVICE_PATH in resp.url:
                reason = ""
                try:
                    reason = (resp.json().get("data") or {}).get("reasonDescription", "")
                except Exception:
                    pass
                captured["device_registered"] = True
                logger.warning(
                    "MS 2FA: device registration processed (account_id=%s, status=%s) %s",
                    account_id, resp.status, reason,
                )
        except Exception:
            pass

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=headless)
            ctx_kwargs: Dict[str, Any] = {"locale": "en-US"}
            # Use the bundled Chromium's own UA but strip the "Headless" token so it
            # matches headful Chrome and stays consistent with every other signal the
            # same Chromium produces (platform, canvas, WebGL, client hints). This
            # removes the "HeadlessChrome" bot-detection tell without faking an
            # inconsistent UA string.
            try:
                probe = browser.new_context()
                ua = probe.new_page().evaluate("() => navigator.userAgent")
                probe.close()
                if ua and "Headless" in ua:
                    ctx_kwargs["user_agent"] = ua.replace("HeadlessChrome", "Chrome")
                    logger.info("MS browser: using de-headlessed UA: %s", ctx_kwargs["user_agent"])
            except Exception as exc:
                logger.warning("MS browser: could not read/sanitize UA: %s", exc)
            if sp and sp.exists():
                ctx_kwargs["storage_state"] = str(sp)
                logger.info("MS browser: loaded device-trust state from %s", sp)
            context = browser.new_context(**ctx_kwargs)
            page = context.new_page()
            page.on("response", _on_response)
            page.set_default_timeout(timeout_ms)

            logger.info("MS browser: navigating to login (headless=%s)", headless)
            page.goto(LOGIN_URL, wait_until="domcontentloaded")

            # If persisted session already lands us on the dashboard, skip login.
            if "/servlet/ui" not in page.url:
                if not _fill_first(page, _USER_SELECTORS, username, timeout_ms):
                    raise BrowserLoginError("Could not find the username field on the login page.")
                if not _fill_first(page, _PASS_SELECTORS, password, timeout_ms):
                    raise BrowserLoginError("Could not find the password field on the login page.")
                if not _click_first(page, _SUBMIT_SELECTORS, timeout_ms):
                    # Fall back to submitting the form by pressing Enter in the password field.
                    page.keyboard.press("Enter")
                page.wait_for_load_state("networkidle")

            # Handle a 2FA (TOTP) challenge if the device is not trusted.
            if _visible_any(page, _TOTP_SELECTORS, timeout_ms=5_000):
                logger.warning("MS 2FA: OTP challenge presented (account_id=%s).", account_id)
                if not allow_otp:
                    raise BrowserLoginError(
                        "OTP challenge presented but OTP is disabled (MS_ALLOW_OTP=0)."
                    )
                # Throttle: refuse to OTP again too soon — repeated 2FA is itself a
                # fraud signal and means device-trust isn't sticking.
                last_otp = _read_last_otp(sp)
                if last_otp is not None and not force_otp:
                    since_h = (time.time() - last_otp) / 3600
                    if since_h < otp_min_secs / 3600:
                        raise BrowserLoginError(
                            f"OTP challenged again only {since_h:.1f}h after the last OTP "
                            f"(throttle {otp_min_secs / 3600:.0f}h, expected ~monthly). "
                            "Device-trust isn't holding — refusing to re-OTP to avoid fraud "
                            "detection. Check the MS_BROWSER_STATE_DIR volume persistence, or "
                            "re-enroll deliberately with MS_FORCE_OTP=1."
                        )
                code = totp_code or (totp_secret and _generate_totp(totp_secret))
                if not code:
                    raise BrowserLoginError(
                        "TOTP challenge presented but no totp_secret/totp_code available."
                    )
                logger.info("MS 2FA: entering TOTP code (account_id=%s).", account_id)
                if not _fill_first(page, _TOTP_SELECTORS, code, timeout_ms):
                    raise BrowserLoginError("Could not fill the TOTP code field.")
                # Trust this device so future syncs skip 2FA (best-effort selector).
                if _click_first(page, _TRUST_SELECTORS, timeout_ms=2_000):
                    logger.warning("MS 2FA: 'trust this device' selected (account_id=%s).", account_id)
                _click_first(page, _TOTP_SUBMIT_SELECTORS, timeout_ms)
                page.wait_for_load_state("networkidle")
                _write_last_otp(sp)
                logger.warning(
                    "MS 2FA: OTP submitted (account_id=%s); next OTP throttled for ~%.0fh.",
                    account_id, otp_min_secs / 3600,
                )
            else:
                logger.info("MS 2FA: no OTP challenge — device trusted (account_id=%s).", account_id)

            # Make sure we reached the authenticated dashboard.
            try:
                page.wait_for_url("**/servlet/ui*", timeout=timeout_ms)
            except Exception:
                if "/servlet/ui" not in page.url:
                    raise BrowserLoginError(
                        f"Login did not reach the dashboard (still at {page.url}). "
                        "Likely bad credentials, an unhandled challenge, or selector drift."
                    )

            # Read identifiers straight from the page's SW.initialData.
            init = page.evaluate(
                "() => { const d = (window.SW && window.SW.initialData) || {};"
                " const a = d.activeAccount || {};"
                " return { employeePK: a.employeePK, accountPK: a.accountPK }; }"
            ) or {}
            employee_pk = init.get("employeePK")
            account_pk = init.get("accountPK")

            # The dashboard mints the token on load; nudge a reload if we missed it.
            if "jwt" not in captured:
                page.wait_for_timeout(1_500)
            if "jwt" not in captured:
                logger.info("MS browser: token not captured yet, reloading dashboard")
                page.goto(DASHBOARD_URL, wait_until="networkidle")
                page.wait_for_timeout(1_500)

            jwt_token = captured.get("jwt")
            if not jwt_token:
                raise BrowserLoginError(
                    "Login succeeded but no JWT was minted/captured "
                    f"({TOKEN_PATH} response not seen)."
                )
            if not employee_pk:
                raise BrowserLoginError("Login succeeded but employeePK was not found in SW.initialData.")

            # Persist the device-trust state for next time.
            state_persisted = False
            if sp:
                try:
                    sp.parent.mkdir(parents=True, exist_ok=True)
                    context.storage_state(path=str(sp))
                    os.chmod(sp, 0o600)
                    state_persisted = True
                    logger.info("MS browser: saved device-trust state to %s", sp)
                except Exception as exc:
                    logger.warning("MS browser: could not persist device-trust state: %s", exc)

            context.close()
            browser.close()

            return {
                "jwt_token": jwt_token,
                "employee_id": str(employee_pk),
                "account_pk": str(account_pk) if account_pk else None,
                "state_persisted": state_persisted,
            }
    except (BrowserLoginUnavailable, BrowserLoginError):
        raise
    except Exception as exc:
        # Surface Playwright launch/driver errors as "unavailable" so callers can
        # fall back to the manual-JWT path instead of hard-failing the sync.
        msg = str(exc).lower()
        if "executable doesn't exist" in msg or "playwright install" in msg or "browsertype.launch" in msg:
            raise BrowserLoginUnavailable(
                "Chromium for Playwright is not installed. Run "
                "`playwright install --with-deps chromium`."
            ) from exc
        raise BrowserLoginError(f"Browser login failed: {exc}") from exc
