# Generated by Django 6.0.3 on 2026-07-12 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_add_supports_auto_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='integration_type',
            field=models.CharField(choices=[('fints', 'FinTS Protocol'), ('rest', 'REST API'), ('graphql', 'GraphQL API'), ('ebics', 'EBICS Protocol')], max_length=20),
        ),
        migrations.CreateModel(
            name='EbicsCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='User-friendly name, e.g. "ZKB DataLink 1234567"', max_length=100)),
                ('host_id', models.CharField(help_text='EBICS Host ID (e.g. ZKBKCHZZ)', max_length=64)),
                ('partner_id', models.CharField(help_text='Partner/Customer ID (Kunden-ID)', max_length=64)),
                ('subscriber_id', models.CharField(help_text='EBICS User/Subscriber ID (Teilnehmer-ID)', max_length=64)),
                ('url', models.URLField(help_text='EBICS endpoint URL')),
                ('bank_hash_auth', models.CharField(blank=True, help_text='Expected SHA-256 hash of the bank authentication (X002) key, hex', max_length=128)),
                ('bank_hash_enc', models.CharField(blank=True, help_text='Expected SHA-256 hash of the bank encryption (E002) key, hex', max_length=128)),
                ('encrypted_keyring', models.BinaryField(blank=True, null=True)),
                ('state', models.CharField(choices=[('new', 'New — keys generated, not yet sent'), ('keys_sent', 'Keys sent — awaiting bank activation'), ('active', 'Active'), ('error', 'Error')], default='new', max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ebics_credentials', to='brokers.broker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebics_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ebics_credentials',
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('user', 'host_id', 'partner_id', 'subscriber_id'), name='unique_ebics_subscriber_per_user')],
            },
        ),
    ]
